### ISSUE TITLE
Modificações para a versão 1

### ISSUE THREAD

**Issue by beatrizmilz** [sicam-iee-usp/sicam#1]
**Página inicial:**

- [x] Adicionar logo na página - Status: esperando o logo
- [x] Adicionar logo no favicon - Status: esperando o logo
- [x] Definir e adicionar imagem de fundo pro carrossel
- [x] Definir e adicionar imagem png usada no carrossel
- [x] Adicionar apoios: USP, PROCAM, IEE - **ADICIONEI LOGOS QUE ENCONTREI NO GOOGLE MAS A RESOLUÇÃO NÃO ESTÁ BOA, SE ALGUÉM TIVER MELHOR EU ADICIONO :)**
- [x] features: alterar os itens apresentados
- [x] Alterar contato no final da página
- [x] Alterar o "somos nós" no final da página

**Páginas para criar (para depois adicionar conteúdo):**

- [x] Equipe organizadora
- [x] Programação do evento
- [x] Regras para submeter trabalhos
- [x] Eventos anteriores

**Parte de estilo:**
- [x] A cor de fundo da sessão de apoio deve ser branca.
- [x] Tirar esse efeito de tons de cinza das imagens da sessão de apoio.
- [x] Centralizar os logos de apoio
- [x] Arrumar os tamanhos dos logos de apoio: todos ter a mesma altura
- [x] Aumentar a fonte para 16 px
- [x] Adicionar um espaço ao final do conteúdo na single page
 
**Conteúdo que precisamos alimentar:**
- [x] Equipe: adicionar as pessoas aqui https://github.com/sicam-iee-usp/sicam/blob/main/content/equipe.csv
- [x] Testimonials: adicionar as pessoas que coordenam GTs aqui: https://github.com/sicam-iee-usp/sicam/tree/main/data/testimonials cada GT tem um arquivo, segundo o número!
- [ ] Adicionar regras de submissão de trabalhos - isso depende de outro grupo

**Comment by camilajh** [comment]
Bia, algumas sugestões:

- [x] Acho que a logo pode ficar menor 
- [x] Trocar o link do formulário de pré-inscrição está errado (dá para a versão de edição, não de "preenchimento"). O link certo é o: https://forms.gle/rTGrGkD7Vj2LfJhL8.
- [x] Veja se fica legal usar a imagem em anexo na home (vale aplicar algum filtro pra ficar apagada, posso fazer isso no canva). Foi a imagem que usei pro header do facebook.
- [ ] Levantar mais imagens de fundo para a home (Camila vai fazer).
- [ ] Escrever texto das páginas: 
    - [x] Programação
    - [ ]  Submissão de trabalhos
    - [x] Sobre o evento.
- [x] Levantar com os outros grupos as informações:
   - [x]  de contato (email e endereço?)
   - [x] equipe (nomes e lattes)
   - [x] coordenadores dos GTs confirmados.

![chris-montgomery-smgTvepind4-unsplash](https://user-images.githubusercontent.com/87432687/125639279-9184455a-27d5-4b79-bb30-98848f099ec1.jpg)

**Comment by beatrizmilz** [comment]
Obrigada @camilajh ! Já fiz alguns desses pontos. 

Sobre as imagens, seria legal buscar uma para:
- [x] O fundo da seção que está escrito "PRÉ-INSCRIÇÃO"
- [ ] Você acha que tá legal essa imagem no fundo da seção com as pessoas coordenadoras dos GTs? https://sicam.netlify.app/img/texture-green.png Se acha que não, podemos mudar.

**Comment by beatrizmilz** [comment]
Sugestões do Rafael Albuquerque:

- [x] Justificar o texto (margens estão desalinhadas) (em sobre o evento)

- [x]  Em “Sobre o evento”, corrigir “Pessoas interessados” para “Pessoas interessadas”

**Comment by beatrizmilz** [comment]
Carrossel dos GTs:

- [x] Centralizar icones
- [x] deixar em 3 linhas

**Comment by beatrizmilz** [comment]
Sugestões Laize:

- [x]  Está assim, né? "O Simpósio Interdisciplinar de Ciência Ambiental (SICAM) é um evento organizado pelo Programa de Ciência Ambiental (PROCAM) do Instituto de Energia e Ambiente da USP. O SICAM nasceu dentro de um programa de pós-graduação interdisciplinar". Sugestão para: "O Simpósio Interdisciplinar de Ciência Ambiental (SICAM) é um evento organizado pelo Programa de Pós-Graduação em  Ciência Ambiental do Instituto de Energia e Ambiente da Universidade de São Paulo (PROCAM/IEE/USP). o SICAM nasceu dentro de um programa interdisciplinar...".

- [x] E a parte que fala da pandemia. Talvez mudar para: " No contexto da pandemia, este terceiro diálogo será de forma virtual..."

**Comment by beatrizmilz** [comment]
- [x] Remover devcows do config.yaml

**Comment by camilajh** [comment]
> Obrigada @camilajh ! Já fiz alguns desses pontos.
> 
> Sobre as imagens, seria legal buscar uma para:
> 
>     * [ ]  O fundo da seção que está escrito "PRÉ-INSCRIÇÃO"
> 
>     * [ ]  Você acha que tá legal essa imagem no fundo da seção com as pessoas coordenadoras dos GTs? https://sicam.netlify.app/img/texture-green.png Se acha que não, podemos mudar.



Com relação às imagens, posso fazer algumas sugestões, Bia?

- [x] Para a seção "PRÉ-INSCRIÇÃO" (que depois vai virar inscrição, certo?), sugiro usarmos a foto que hoje está sendo usada no 1o bloco (a que tem o computador com a videoconferência). 
- [x] Também seria legal se essa sessão subisse, viesse antes dos GTs.

- [x] Aí, no 1o bloco, atrás da logo podemos usar alguma das texturas que pus no drive, [como essa](https://drive.google.com/file/d/1nI4W6y9TDNGI6r0Th35qjlyqY-Ir5c9F/view?usp=sharing), ou então [essa arte aqui](https://drive.google.com/file/d/1Il3s04rjGuXcsFGsHqpmlyCgvO4SyZ1c/view?usp=sharing) que criei para usarmos de header. 

- [x] Para o fundo dos GTs, [criei uma imagem no canva](https://drive.google.com/file/d/1G89oHj16BCpXyWGtn3VGsQnBzJL_6Wjy/view?usp=sharing), veja se fica bom.
